[target.xtensa-esp32s3-none-elf]
# runner = "probe-rs run --chip=esp32s3 --preverify --always-print-stacktrace --no-location --catch-hardfault"
runner = "espflash flash -B 921600 -L defmt --partition-table partitions.csv"

[env]
DEFMT_LOG = "info"
# Path to lv_conf.h for lightvgl-sys
DEP_LV_CONFIG_PATH = { value = "./lv_conf/", relative = true }
# point CC to the esp compiler
CC_xtensa_esp32s3_none_elf = "xtensa-esp32s3-elf-gcc"
# Bindgen needs explicit target for host builds (esp-clang lib defaults wrong)
BINDGEN_EXTRA_CLANG_ARGS_x86_64_unknown_linux_gnu = "--target=x86_64-unknown-linux-gnu"

[build]
target = "xtensa-esp32s3-none-elf"
rustflags = ["-C", "link-arg=-nostartfiles"]

[unstable]
build-std = ["alloc", "core"]
