[target.xtensa-esp32s3-none-elf]
# runner = "probe-rs run --chip=esp32s3 --preverify --always-print-stacktrace --no-location --catch-hardfault"
runner = "espflash flash -B 921600 -L defmt"

[env]
DEFMT_LOG = "info"
# Tell esp-hal to compile the PSRAM driver in Octal mode
# ESP_HAL_CONFIG_PSRAM_MODE = "octal"

[build]
target = "xtensa-esp32s3-none-elf"
rustflags = ["-C", "link-arg=-nostartfiles"]

[unstable]
build-std = ["alloc", "core"]
