export global Theme {
    in-out property <bool> dark_mode: true;

    out property <color> base: dark_mode ? #1e1e2e : #eff1f5;
    out property <color> mantle: dark_mode ? #181825 : #e6e9ef;
    out property <color> surface0: dark_mode ? #313244 : #ccd0da;
    out property <color> surface1: dark_mode ? #45475a : #bcc0cc;
    out property <color> surface2: dark_mode ? #585b70 : #acb0be;
    out property <color> text: dark_mode ? #cdd6f4 : #4c4f69;
    out property <color> subtext: dark_mode ? #a6adc8 : #6c6f85;
    out property <color> accent: dark_mode ? #89b4fa : #1e66f5;
    out property <color> accent2: dark_mode ? #cba6f7 : #8839ef;
    out property <color> green: dark_mode ? #a6e3a1 : #40a02b;
    out property <color> yellow: dark_mode ? #f9e2af : #df8e1d;
    out property <color> red: dark_mode ? #f38ba8 : #d20f39;
    out property <color> peach: dark_mode ? #fab387 : #fe640b;
    out property <color> sky: dark_mode ? #89dceb : #04a5e5;
    out property <color> lavender: dark_mode ? #b4befe : #7287fd;
}
